print("Biodata")

nama = input("ketik nama lengkap: ")
tempat_dan_tanggal_lahir = input("ketik tempat lahir dan tanggal lahir (dd/mm/yyyy): ")
jenis_kelamin = input("ketik jenis kelamin: ")
alamat = input("ketik alamat: ")
no_telp = input("krtik nomor telepon: ")
email = input("ketik alamat email: ")
pendidikan = input("ketik pendidikan terakhir: ")
status_perkawinan = input("ketik status: ")

print("Nama Lengkap                 :", nama)
print("Tempat, Tanggal Lahir        :", tempat_dan_tanggal_lahir)
print("Jenis kelamin                :", jenis_kelamin)
print("Alamat                       :", alamat)
print("No. Telepon                  :", no_telp)
print("Email                        :", email)
print("Pendidikan terakhir          :", pendidikan)
print("Status perkawinan            :", status_perkawinan)